version: "3"
services:
  proxy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  server:
    privileged: true
    environment:
      - PULSE_SERVER=docker.for.mac.localhost
    build:
      context: ./audioNode
      dockerfile: Dockerfile
    volumes:
      - audio:/audioNode/audio
      - ~/.config/pulse:/home/pulseaudio/.config/pulse

    ports:
      - "8080:8080"
      - "8888:8888"

    depends_on:
      - proxy

volumes:
  audio:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/Desktop/Techno
