# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import analyzer_pb2 as analyzer__pb2


class AnalyzerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.initAnalyzer = channel.unary_unary(
                '/analyzer.AnalyzerService/initAnalyzer',
                request_serializer=analyzer__pb2.InitRequest.SerializeToString,
                response_deserializer=analyzer__pb2.InitResponse.FromString,
                )
        self.analyzeStream = channel.unary_unary(
                '/analyzer.AnalyzerService/analyzeStream',
                request_serializer=analyzer__pb2.StreamData.SerializeToString,
                response_deserializer=analyzer__pb2.DataPoints.FromString,
                )


class AnalyzerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def initAnalyzer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def analyzeStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyzerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'initAnalyzer': grpc.unary_unary_rpc_method_handler(
                    servicer.initAnalyzer,
                    request_deserializer=analyzer__pb2.InitRequest.FromString,
                    response_serializer=analyzer__pb2.InitResponse.SerializeToString,
            ),
            'analyzeStream': grpc.unary_unary_rpc_method_handler(
                    servicer.analyzeStream,
                    request_deserializer=analyzer__pb2.StreamData.FromString,
                    response_serializer=analyzer__pb2.DataPoints.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analyzer.AnalyzerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AnalyzerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def initAnalyzer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analyzer.AnalyzerService/initAnalyzer',
            analyzer__pb2.InitRequest.SerializeToString,
            analyzer__pb2.InitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def analyzeStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/analyzer.AnalyzerService/analyzeStream',
            analyzer__pb2.StreamData.SerializeToString,
            analyzer__pb2.DataPoints.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
