# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyzer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='analyzer.proto',
  package='analyzer',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x61nalyzer.proto\x12\x08\x61nalyzer\"\"\n\x0bInitRequest\x12\x13\n\x0binitMessage\x18\x01 \x01(\t\"+\n\x0cInitResponse\x12\x1b\n\x13initResponseMessage\x18\x01 \x01(\t\"\"\n\tTrackData\x12\x15\n\rtrackFileName\x18\x01 \x01(\t\"#\n\nStreamData\x12\x15\n\rtrackFileName\x18\x01 \x01(\t\"\x0c\n\nDataPoints2\xcc\x01\n\x14TrackAnalyzerService\x12=\n\x0cinitAnalyzer\x12\x15.analyzer.InitRequest\x1a\x16.analyzer.InitResponse\x12\x38\n\x0bstreamTrack\x12\x13.analyzer.TrackData\x1a\x14.analyzer.DataPoints\x12;\n\ranalyzeStream\x12\x14.analyzer.StreamData\x1a\x14.analyzer.DataPointsb\x06proto3'
)




_INITREQUEST = _descriptor.Descriptor(
  name='InitRequest',
  full_name='analyzer.InitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='initMessage', full_name='analyzer.InitRequest.initMessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=62,
)


_INITRESPONSE = _descriptor.Descriptor(
  name='InitResponse',
  full_name='analyzer.InitResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='initResponseMessage', full_name='analyzer.InitResponse.initResponseMessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=107,
)


_TRACKDATA = _descriptor.Descriptor(
  name='TrackData',
  full_name='analyzer.TrackData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='trackFileName', full_name='analyzer.TrackData.trackFileName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=143,
)


_STREAMDATA = _descriptor.Descriptor(
  name='StreamData',
  full_name='analyzer.StreamData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='trackFileName', full_name='analyzer.StreamData.trackFileName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=180,
)


_DATAPOINTS = _descriptor.Descriptor(
  name='DataPoints',
  full_name='analyzer.DataPoints',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=194,
)

DESCRIPTOR.message_types_by_name['InitRequest'] = _INITREQUEST
DESCRIPTOR.message_types_by_name['InitResponse'] = _INITRESPONSE
DESCRIPTOR.message_types_by_name['TrackData'] = _TRACKDATA
DESCRIPTOR.message_types_by_name['StreamData'] = _STREAMDATA
DESCRIPTOR.message_types_by_name['DataPoints'] = _DATAPOINTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InitRequest = _reflection.GeneratedProtocolMessageType('InitRequest', (_message.Message,), {
  'DESCRIPTOR' : _INITREQUEST,
  '__module__' : 'analyzer_pb2'
  # @@protoc_insertion_point(class_scope:analyzer.InitRequest)
  })
_sym_db.RegisterMessage(InitRequest)

InitResponse = _reflection.GeneratedProtocolMessageType('InitResponse', (_message.Message,), {
  'DESCRIPTOR' : _INITRESPONSE,
  '__module__' : 'analyzer_pb2'
  # @@protoc_insertion_point(class_scope:analyzer.InitResponse)
  })
_sym_db.RegisterMessage(InitResponse)

TrackData = _reflection.GeneratedProtocolMessageType('TrackData', (_message.Message,), {
  'DESCRIPTOR' : _TRACKDATA,
  '__module__' : 'analyzer_pb2'
  # @@protoc_insertion_point(class_scope:analyzer.TrackData)
  })
_sym_db.RegisterMessage(TrackData)

StreamData = _reflection.GeneratedProtocolMessageType('StreamData', (_message.Message,), {
  'DESCRIPTOR' : _STREAMDATA,
  '__module__' : 'analyzer_pb2'
  # @@protoc_insertion_point(class_scope:analyzer.StreamData)
  })
_sym_db.RegisterMessage(StreamData)

DataPoints = _reflection.GeneratedProtocolMessageType('DataPoints', (_message.Message,), {
  'DESCRIPTOR' : _DATAPOINTS,
  '__module__' : 'analyzer_pb2'
  # @@protoc_insertion_point(class_scope:analyzer.DataPoints)
  })
_sym_db.RegisterMessage(DataPoints)



_TRACKANALYZERSERVICE = _descriptor.ServiceDescriptor(
  name='TrackAnalyzerService',
  full_name='analyzer.TrackAnalyzerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=197,
  serialized_end=401,
  methods=[
  _descriptor.MethodDescriptor(
    name='initAnalyzer',
    full_name='analyzer.TrackAnalyzerService.initAnalyzer',
    index=0,
    containing_service=None,
    input_type=_INITREQUEST,
    output_type=_INITRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='streamTrack',
    full_name='analyzer.TrackAnalyzerService.streamTrack',
    index=1,
    containing_service=None,
    input_type=_TRACKDATA,
    output_type=_DATAPOINTS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='analyzeStream',
    full_name='analyzer.TrackAnalyzerService.analyzeStream',
    index=2,
    containing_service=None,
    input_type=_STREAMDATA,
    output_type=_DATAPOINTS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRACKANALYZERSERVICE)

DESCRIPTOR.services_by_name['TrackAnalyzerService'] = _TRACKANALYZERSERVICE

# @@protoc_insertion_point(module_scope)
